### ISSUE TITLE
invalid number

### ISSUE THREAD

**Issue by LxCasino** [evonshahriar/stock-cli#2]
![Screenshot-20200323133711-1222x220](https://user-images.githubusercontent.com/48494338/77318954-41417500-6d0e-11ea-896e-e5fdc7f12132.png)

**Comment by evonshahriar** [comment]
Don't know what's causing the problem. Can you please change the shebang to #!/usr/bin/env bash and try to upgrade the jq?  If that doesn't help, please let me know the environment you're currently using to run the script. Thank you!

**Comment by LxCasino** [comment]
I'm just using zsh as an alternative to bash.

**Comment by evonshahriar** [comment]
I see. As far as I know, zsh has most features of bash, but in many cases with a different syntax. You can still use the script by changing the shebang line to `#!/usr/bin/env bash`.

And jq is a command-line JSON processor. Unfortunately, shells such as bash can’t interpret and work with JSON directly. That's why I've used jq because the built-in functions that come bundled with jq, really make it easy to work with JSON data without using various text manipulation tools like grep, sed, awk etc. You can find out more about that here: https://stedolan.github.io/jq/

**Comment by LxCasino** [comment]
Thank you.
I edited the shebang line to `#!/usr/bin/env bash` and got jq. I didn't do anything with jq though. Do I need to configure it to make it work?
Still no fix as of now.

**Comment by evonshahriar** [comment]
Having jq installed should be enough for the script to run. 
I've installed zsh shell on my Linux system to recreate the issue you're facing. But it didn't show any errors for me. Seems like we'll have to keep the help tag open for some time.
[zsh-shell](https://user-images.githubusercontent.com/43861217/77369566-2102cc00-6d89-11ea-9e33-e8d1be80cba9.png)

**Comment by szepczynski** [comment]
To resolve problem with invalid number please add at the beginning:
`export LC_NUMERIC="en_US.UTF-8"`
